package gate

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// GenFile is one generated page: its slash-separated path relative to the
// repository root, and its content.
type GenFile struct {
	Path    string
	Content string
}

const genHeader = "<!-- Generated by `gate gen` from the rule pages' front matter. Do not edit: run `task gen`. -->\n\n"

var (
	groupTitles = map[string]string{
		"ownership":     "Ownership & lifetime",
		"shared-memory": "Shared memory",
		"coordination":  "Coordination",
		"time":          "Time",
		"testing":       "Testing",
		"measurement":   "Measurement",
	}
	tagTitles = map[string]string{
		"read":     "Reading concurrent code",
		"write":    "Writing it",
		"refactor": "Refactoring it",
		"test":     "Testing it",
		"profile":  "Profiling it",
	}
)

// Generate renders the index pages: one per group, one per activity tag, and
// the Retired index. It is a pure function of the rules — the same rules give
// the same bytes — so CI can regenerate and compare (StaleGenerated).
//
// Every group and every activity gets a page, even with no rules in it yet,
// so the site's navigation never points at a missing page.
func Generate(rules []Rule) []GenFile {
	rules = slices.Clone(rules)
	slices.SortFunc(rules, func(a, b Rule) int { return strings.Compare(a.ID, b.ID) })
	var active, retired []Rule
	for _, r := range rules {
		if r.Status == "retired" {
			retired = append(retired, r)
		} else {
			active = append(active, r)
		}
	}

	var files []GenFile
	for _, g := range groups {
		in := slices.DeleteFunc(slices.Clone(active), func(r Rule) bool { return r.Group != g })
		files = append(files, GenFile{
			Path:    "docs/groups/" + g + ".md",
			Content: rulesPage(groupTitles[g], in),
		})
	}
	for _, tag := range tags {
		in := slices.DeleteFunc(slices.Clone(active), func(r Rule) bool { return !slices.Contains(r.Tags, tag) })
		files = append(files, GenFile{
			Path:    "docs/activity/" + tag + ".md",
			Content: rulesPage(tagTitles[tag], in),
		})
	}
	files = append(files, GenFile{Path: "docs/retired/index.md", Content: retiredPage(retired)})
	return files
}

// rulesPage lists active rules, linked from a page one directory below docs/.
func rulesPage(title string, rules []Rule) string {
	var b strings.Builder
	b.WriteString(genHeader)
	fmt.Fprintf(&b, "# %s\n\n", title)
	if len(rules) == 0 {
		b.WriteString("No rules here yet.\n")
		return b.String()
	}
	b.WriteString("| Rule | Statement | Since | Proof |\n|---|---|---|---|\n")
	for _, r := range rules {
		fmt.Fprintf(&b, "| [%s — %s](../rules/%s.md) | %s | %s | %s |\n",
			r.ID, cell(r.Title), r.Slug, cell(r.Statement), r.Since, r.Proof.Kind)
	}
	return b.String()
}

// retiredPage lists retired entries, linked from docs/retired/index.md.
func retiredPage(rules []Rule) string {
	var b strings.Builder
	b.WriteString(genHeader)
	b.WriteString("# Retired rules\n\n")
	b.WriteString("Rules that were golden and expired. Each says which Go version retired it, what\n")
	b.WriteString("replaced it, and what residue remains — and carries a proof where one is still\n")
	b.WriteString("possible.\n\n")
	if len(rules) == 0 {
		b.WriteString("No rules have been retired yet.\n")
		return b.String()
	}
	b.WriteString("| Entry | Retired in | Replaced by | Proof |\n|---|---|---|---|\n")
	for _, r := range rules {
		fmt.Fprintf(&b, "| [%s — %s](%s.md) | %s | %s | %s |\n",
			r.ID, cell(r.Title), r.Slug, r.RetiredIn, cell(r.ReplacedBy), r.Proof.Kind)
	}
	return b.String()
}

// cell makes text safe inside a Markdown table cell: a pipe would end it.
func cell(s string) string {
	return strings.ReplaceAll(s, "|", `\|`)
}

// StaleGenerated returns the paths, sorted, of generated pages that are
// missing under root or differ from what Generate produces now.
func StaleGenerated(root string, files []GenFile) []string {
	var stale []string
	for _, f := range files {
		data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(f.Path)))
		if err != nil || !bytes.Equal(data, []byte(f.Content)) {
			stale = append(stale, f.Path)
		}
	}
	slices.Sort(stale)
	return stale
}

// WriteGenerated writes every generated page under root.
func WriteGenerated(root string, files []GenFile) error {
	for _, f := range files {
		p := filepath.Join(root, filepath.FromSlash(f.Path))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(p, []byte(f.Content), 0o644); err != nil {
			return err
		}
	}
	return nil
}
