package gate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// genRules is a small catalog: two active rules in different groups and
// activities, and one retired entry.
func genRules() []Rule {
	return []Rule{
		{
			ID: "R09", Title: "Acquire locks in one global order", Statement: "Lock in one order.",
			Group: "shared-memory", Tags: []string{"read", "write"}, Since: "go1.0", Status: "active",
			Proof: Proof{Kind: "test"}, Slug: "r09-order", Page: "docs/rules/r09-order.md",
		},
		{
			ID: "R07", Title: "A data race is a missing edge", Statement: "Add the edge | not a sleep.",
			Group: "shared-memory", Tags: []string{"read"}, Since: "go1.0", Status: "active",
			Proof: Proof{Kind: "race"}, Slug: "r07-race", Page: "docs/rules/r07-race.md",
		},
		{
			ID: "X01", Title: "Copy the loop variable", Statement: "Copy it.",
			Group: "ownership", Tags: []string{"write"}, Since: "go1.0", Status: "retired",
			RetiredIn: "go1.22", ReplacedBy: "per-iteration loop variables",
			Proof: Proof{Kind: "test"}, Slug: "x01-copy", Page: "docs/retired/x01-copy.md",
		},
	}
}

func TestGenerate(t *testing.T) {
	files := map[string]string{}
	for _, f := range Generate(genRules()) {
		files[f.Path] = f.Content
	}

	// One page per group, one per activity, and the Retired index — even
	// for groups with no rules yet, so the site's navigation never dangles.
	if want := len(groups) + len(tags) + 1; len(files) != want {
		t.Fatalf("got %d files, want %d: %v", len(files), want, keys(files))
	}
	for _, g := range groups {
		if _, ok := files["docs/groups/"+g+".md"]; !ok {
			t.Errorf("missing docs/groups/%s.md", g)
		}
	}

	shared := files["docs/groups/shared-memory.md"]
	for _, want := range []string{
		"Generated by `gate gen`",
		"# Shared memory",
		"[R07 — A data race is a missing edge](../rules/r07-race.md)",
		`Add the edge \| not a sleep.`, // a pipe would end the table cell
	} {
		if !strings.Contains(shared, want) {
			t.Errorf("shared-memory page lacks %q:\n%s", want, shared)
		}
	}
	if i, j := strings.Index(shared, "R07"), strings.Index(shared, "R09"); i < 0 || j < 0 || i > j {
		t.Errorf("rules are not listed in ID order:\n%s", shared)
	}
	if strings.Contains(shared, "X01") {
		t.Errorf("a retired entry is listed among the active rules:\n%s", shared)
	}
	if empty := files["docs/groups/time.md"]; !strings.Contains(empty, "No rules here yet") {
		t.Errorf("an empty group page should say so:\n%s", empty)
	}

	read := files["docs/activity/read.md"]
	if !strings.Contains(read, "R07") || !strings.Contains(read, "R09") {
		t.Errorf("activity page lacks a rule tagged read:\n%s", read)
	}
	if strings.Contains(files["docs/activity/write.md"], "R07") {
		t.Errorf("R07 is not tagged write but is listed there")
	}

	retired := files["docs/retired/index.md"]
	for _, want := range []string{"[X01 — Copy the loop variable](x01-copy.md)", "go1.22", "per-iteration loop variables"} {
		if !strings.Contains(retired, want) {
			t.Errorf("retired index lacks %q:\n%s", want, retired)
		}
	}
}

func TestStaleGenerated(t *testing.T) {
	root := t.TempDir()
	files := Generate(genRules())
	for _, f := range files {
		p := filepath.Join(root, filepath.FromSlash(f.Path))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(f.Content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	if stale := StaleGenerated(root, files); len(stale) != 0 {
		t.Fatalf("freshly written files reported stale: %v", stale)
	}

	edited := filepath.Join(root, "docs", "groups", "time.md")
	if err := os.WriteFile(edited, []byte("hand edit\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Remove(filepath.Join(root, "docs", "activity", "profile.md")); err != nil {
		t.Fatal(err)
	}
	stale := StaleGenerated(root, files)
	if strings.Join(stale, ",") != "docs/activity/profile.md,docs/groups/time.md" {
		t.Fatalf("stale = %v, want the deleted and the edited page", stale)
	}
}

func keys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}
